### ISSUE TITLE
Questions about dataset and augment

### ISSUE THREAD

**Issue by 777777ls** [MihawkHu/DCASE2020_task1#12]
Hi,
I have two questions：
1. Is the training file wrong? 'train_csv = 'evaluation_setup/fold1_train_full.csv''
2. Are totally 9 data augmentation methods used in this project？How to used the audio_based and spectrum_correction method?
I will really appreciate your kindness.

**Comment by MihawkHu** [comment]
Hi, 

Thanks for your interests. For your questions:
1. The train_csv can be assigned by you. For example, if you want to use the original training set, use 'fold1_train.csv'. Otherwise, u can add agumented data names into the csv file, like in 'fold1_train_all.csv'.
2. In our final systems, we used all data augmentation methods we mentioned. Please refer to the fold 'https://github.com/MihawkHu/DCASE2020_task1/tree/master/task1a/data_augmentation/' for more details about how to generating augmented data.
